bibliography: references.bib
cls: evolution.csl

format:
  html:
    theme:
      - cosmo
      - brand
    anchor-sections: true
    embed-resources: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
