---
title: Calibrating selection of comparative biogeographic models with hyperpriors
authors:
  - name: João Fentanes Machado
    affiliation:
      - id: fsp
        name: Universidade Federal de São Paulo
        city: São Paulo
        country: Brazil
  - name: Jamie Oaks
    orcid: 0000-0002-3757-3836
    url: https://phyletica.org
    corresponding: true
    email: joaks@auburn.edu
    affiliation:
      - id: aumnh
        name: Auburn University Museum of Natural History
        city: Auburn
        state: AL
        country: USA
        url: https://aumnh.auburn.edu/
      - id: audbs
        name: Auburn University Department of Biological Sciences
        city: Auburn
        state: AL
        country: USA
        url: https://www.auburn.edu/cosam/departments/biology/index.htm
abstract: |
  In comparative biogeographic methods like msbayes and ecoevolity, prior distributions on divergence times with lots of uncertainty can create a strong
  penalty against models with more divergence-time parameters, and thus cause a downward bias in the number of divergence events across the taxa being
  compared. For this project, we will explore whether a hierarchical Bayesian approach can mitigate such a bias. Specifically, we will explore using
  hyperpriors on the parameters of the prior on divergence times to see if the model can learn about the divergence-time prior during the analysis and
  better calibrate the “penalty” against adding divergence-time parameters to the model.
  
keywords:
  - biogeography
  - comparative phylogeography
  - Bayesian model choice
  - Bayesian hyperprior
number-sections: true
crossref:
  fig-title: Figure
  tbl-title: Table
  title-delim: "."
  fig-prefix: Figure
  tbl-prefix: Table
  ref-hyperlink: true
  custom:
    - kind: float
      key: sfig
      latex-env: sfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: SI Figure
---

## Introduction
Reconstructing the timing of evolutionary events is fundamental for understanding key processes in evolutionary biology,
including the mechanisms driving lineage diversification, the emergence of biogeographic patterns, and the assembly of regional biodiversity. 
<!-- Citations for the sentence above would be helpful -->
A central question in comparative phylogeography is whether codistributed lineages have responded synchronously
to shared historical events or whether each lineage has a unique divergence history [@Avise2000; @Hickerson2006MolEcol].
<!-- TODO for Jamie: This might be a good place to introduce the Philippine PAIC diversification hypothesis -->
Distinguishing between these
scenarios requires accurate estimates of divergence times across multiple co-distributed population pairs, as well as robust statistical methods
for inferring whether those divergence times are shared or independent. 

Bayesian approaches have become the standard for estimating divergence times because they provide a principled framework for integrating prior
biological knowledge while explicitly propagating uncertainty across model parameters [@Drummond2007; @Yang2006].
In the context of comparative phylogeography, Bayesian methods have been developed to simultaneously estimate divergence times across multiple
taxon pairs and infer the degree to which those divergences are clustered in time, that is, whether lineages diverged synchronously or 
asynchronously [@Hickerson2006; @Oaks2018ecoevolity]. Both simulation-based [@Hickerson2006; @Huang2011] and full-likelihood [@Oaks2018ecoevolity;
@Oaks2019codemog] implementations of this framework have been proposed, enabling rigorous tests of synchronous divergence hypotheses.
<!-- Are there other simulation-based implementations that might be worth citing? -->

However, these methods can be biased toward over-clustering divergence events (i.e., underestimating the number of divergence times) [@Oaks2012;
@Oaks2014reply]. This bias can lead to spurious inferences of synchronous divergence, with potentially misleading implications for our understanding
of the historical processes structuring biodiversity. @Oaks2014reply proposed this tendency to prefer models with too few divergence-time parameters
was caused by the prior probability density placed on the divergence times of the population pairs.
In Bayesian model choice, the posterior probability of a model is informed by
the data through the model's marginal likelihood, which is the likelihood
averaged over the model's parameter space, weighted by the prior [@Jeffreys1935].
As a result, the prior serves as a "penalty" for adding parameters to a model.
When the prior on divergence times is broad, as is necessary when there is genuine prior uncertainty about when lineages diverged, it
can place substantial probability density across divergence times with small likelihood, reducing the average (marginal) likelihood of models with many distinct
divergences among the pairs of populations. As a result, models that collapse multiple divergence times into fewer shared events are often 
favored, not because the data support synchrony, but because the broad prior penalizes complexity. Specifying a prior more concentrated on divergence times with larger likelihoods would reduce this
tendency [@Lindley1957], but doing so requires strong *a priori* knowledge about divergence times that is rarely available in practice, creating a difficult trade-off
between expressing appropriate uncertainty and avoiding inferential bias.

A natural solution to this problem is to move the uncertainty up one level
in the model hierarchy: rather than fixing the parameters of the divergence-time prior, one can place hyperpriors over those parameters and allow the
data to inform the prior during inference [@LindleySmith1972; @Good1980].
Here, we implement such a hierarchical model in ecoevolity [@Oaks2018ecoevolity], allowing hyperpriors to be specified for one or more parameters of the divergence-time
prior, so that the distribution of prior density over the space of divergence times is estimated jointly with all other model parameters. This approach allows the model to
adaptively learn the distribution of divergence times from the data, avoiding the need to commit to fixed parameters of a prior whose breadth may
create a strong preference for models with too few divergences. Using simulated comparative biogeographic data and empirical genomic data from Philippine geckos, we
(i) characterize the downward tendency in the estimated number of divergence events caused by prior uncertainty about the timing of divergence,
and (ii) show that hyperpriors on the parameters of the divergence-time prior effectively mitigate this bias and recover more accurate estimates of the number of
divergence events.

## Methods

### Ecoevolity implementation of hyperpriors on divergence-time prior parameters

<!-- TODO for Jamie: Include technical details here -->

### Analyses of simulated data

To validate the hyperprior implementation and assess its ability to
mitigate the underestimation of the number of divergence times,
we used the `simcoevolity` and `ecoevolity` tools within the ecoevolity software
package
[Version X.X, Commit XXXX; @Oaks2018ecoevolity]
to simulate and analyze data, respectively.
Each simulated data set comprised 20,000 unlinked biallelic characters from two
diploid individuals (4 genomes) sampled per population from 20 pairs of populations.

We specified a gamma distribution on the concentration parameter of the
Dirichlet process, $\alpha$, so that the mean number of unique divergence times
across the 20 pairs of populations was approximately 10.8
($\alpha \sim \textsf{Gamma}(\textsf{shape} = 4.0, \textsf{mean} = 10)$).
We assumed the mutation rates of the 20 pairs of populations were equal and 1,
making time and the effective population sizes scaled by the mutation rate.
We also assumed the stationary frequencies of the two character states of the
biallelic characters were equal.
For each pair of populations, we assumed both populations and their common
ancestral population shared the same mutation-scaled effective size that was
constant through time and drawn from a gamma distribution
($N_e \sim \textsf{Gamma}(\textsf{shape} = 10.0, \textsf{mean} = 0.0005)$).
In other words, the pairs of populations have independent effective population
sizes that are constant throughout each of their divergence histories.

When analyzing each simulated data set, we used the distributions above as
priors and four independent chains of Markov chain Monte Carlo (MCMC),
each run for 60,000 generations with a sample collected every 40 generations,
for a total of 1,501 samples per chain (including the initial state of the
chain).
We chose to summarize the last 1,300 samples from each chain for a total of
5,200 samples to approximate the posterior distribution for each simulated data
set.
To inform our choice to ignore the first 201 samples from each chain,
from preliminary analyses,
we calculated the 
potential scale reduction factor
[PSRF; the square root of Equation 1.1 in @Brooks1998]
and effective sample size [ESS; @Gong2014] from the four chains for all continuous
parameters and the log likelihood using the `pyco-sumchains` tool of
pycoevolity (Version X.X Commit XXXX).
Based on these summaries from preliminary analyses, chains were consistently
converging to a stationary distribution well before Sample 201.
When plotting results, we highlight any parameter estimate that has a
$\textsf{PSRF} > 1.2$ or $\textsf{ESS} < 200$.

#### Validating prior sampling and posterior coverage 

Prior to evaluating the performance of hyperpriors in mitigating the
underestimation of the number of divergence times, we validated the ecoevolity
implementation of hyperpriors on divergence-time prior parameters by confirming
the MCMC algorithms correctly sample from the prior distribution when data are
ignored and have the correct posterior coverage when analyzing simulated data.

##### Prior sampling

To confirm that ecoevolity correctly samples from the specified prior
distribution in the absence of data, we ran the MCMC sampler with no likelihood
contribution from the data, effectively sampling from the prior alone.
Under this condition, the resulting marginal distributions of all parameters
should match the expected prior distributions.
Significant deviations would indicate an implementation error in the prior
specification or the sampler itself.

We did this for two model prior distributions,
both using the assumptions and distributions described above.
One used an exponentially distributed hyperprior on the mean
of an exponentially distributed prior on divergence times:
$\tau \sim \textsf{Exponential}(\textsf{mean} \sim \textsf{Exponential}(\textsf{mean} = 0.2))$.
The other used a uniformly distributed hyperprior on the maximum
of a uniformly distributed prior on divergence times:
$\tau \sim \textsf{Uniform}(0, \textsf{max} \sim \textsf{Uniform}(0, 0.2))$.

##### Posterior coverage

To validate that the posterior credible intervals produced
by ecoevolity achieve the correct nominal coverage when analyzing data
simulated under a model with divergence-time hyperpriors, we simulated and
subsequently analyzed 100 data sets under the same two models with hyperpriors on
divergence-time parameters:
$\tau \sim \textsf{Exponential}(\textsf{mean} \sim \textsf{Exponential}(\textsf{mean} = 0.2))$
and
$\tau \sim \textsf{Uniform}(0, \textsf{max} \sim \textsf{Uniform}(0, 0.2))$.
For each analyzed simulated data set, we recorded whether the true value of the
divergence-time parameter (the mean of the exponentially distributed prior or
max of the uniformly distributed prior), fell within the 50% posterior credible
interval.
If the hyperprior implementation works correctly,
the proportion of simulation replicates for which the true value is contained
within the 50% credible interval should be approximately 0.5.
Systematic under or overcoverage would indicate miscalibration of the
posterior. 

#### Demonstrating bias imposed by fixed diffuse time priors and assessing hyperpriors as a solution

To demonstrate the underestimation of the number of divergences when there is
prior uncertainty about divergence times (i.e., the prior on divergence times
is more diffuse than the true generating distribution), we simulated data under
a more concentrated distribution on divergence times and then analyzed those
data sets using a more diffuse prior on divergence times.
We also analyzed each dataset under the true (more concentrated) prior
distribution to serve as a best-case scenario for comparison.
<!-- We will probably want to move the following sentence to the results or
discussion, but leaving here for now -->
If our hypothesis about the cause of the downward bias on the number of
divergence times is correct, we expect the results of these analyses to show
a tendency to underestimate the number of divergence events across pairs of
populations when using the diffuse prior, but not the concentrated prior.

We evaluated two divergence-time distributions: exponential, because waiting times for random events tend
to be exponentially distributed, and uniform, because the underestimation of the number of divergence events
was first recognized in the context of uniform priors on divergence times [@Oaks2012; @Hickerson2013; @Oaks2014reply].
For both distributions, the clustering of the 20 pairs of populations to
divergence times is randomly determined by the Dirichlet process distribution
described above.
For the exponential distribution, each unique divergence time is drawn from an
exponential distribution with a mean of 0.01 expected substitutions per site
($\tau \sim \textsf{Exponential}(\textsf{mean} = 0.01)$).
We then analyzed each simulated data set under three models that only differ in
their prior on unique divergence times:

1.  The true distribution, serving as the best case for comparison:
    $\tau \sim \textsf{Exponential}(\textsf{mean} = 0.01)$.
2.  A diffuse prior on divergence times: $\tau \sim \textsf{Exponential}(\textsf{mean} = 0.2)$.
3.  A hyperprior model that places an exponentially distributed hyperprior on
    the mean of an exponentially distributed divergence-time prior:
    $\tau \sim \textsf{Exponential}(\textsf{mean} \sim \textsf{Exponential}(\textsf{mean} = 0.2))$.

For the uniform distribution, each unique divergence time is drawn from an
uniform distribution with a maximum of 0.02 expected substitutions per site
($\tau \sim \textsf{Uniform}(0, 0.02)$).
Like with the exponential distribution,
we analyzed each simulated data set under three models:

1.  The true distribution:
    $\tau \sim \textsf{Uniform}(0, 0.02)$.
2.  A diffuse prior on divergence times:.
    $\tau \sim \textsf{Uniform}(0, 0.2)$.
3.  A hyperprior model that places an uniformly distributed hyperprior on
    the maximum of a uniformly distributed divergence-time prior:
    $\tau \sim \textsf{Uniform}(0, \textsf{max} \sim \textsf{Uniform}(0, 0.2))$.

For the exponential and uniform distributions, the hyperprior model expresses
the greatest amount of uncertainty, but allows the data to inform the
distribution of divergence times.

Model performance was assessed via
the proportion of analyses that result in the underestimation of the number of
divergence times,
the proportion of analyses for which the true number of divergence times is
contained within the 95% credible set,
the median (across simulation replicates) posterior probability of the true
number of divergences, and the posterior rank sum of the true divergence model
(clustering of pairs of populations to unique divergence times).

### Testing the PAIC diversification model for Philippine gekkonids

To test the hypothesis that the repeated joining and fragmentation of
Pleistocene aggregate island complexes (PAIC) in the Philippines caused bursts
of speciation,
we reanalyzed the RADseq data of @Oaks2018paic from 16 inter-island pairs of
gecko populations from across the Philippine islands.
These data include eight pairs each of *Cyrtodactylus* and *Gekko* populations,
which were originally analyzed separately due to the lack of information about
the relative rates of mutation between the genera.
To analyze all 16 pairs together,
we estimated the mutation rate for the Philippine radiations of both genera
using estimates of node ages from published calibrated phylogenetic analyses
and the phylogeny of @Oaks2021phycoeval of both genera across the Philippines
based on an assembly of the same RADseq data we analyze here.

To get the rate of mutation for *Cyrtodactylus* per million years, we divided
the mean age of the root of the Philippine *Cyrtodactylus* phylogeny from
@Oaks2021phycoeval in units of expected substitutions per site by 23.07 million years, the
estimated age of this node by @Grismer2022peerj.
For *Gekko*,
we divided the mean age of the root of the Philippine *Gekko* phylogeny from
@Oaks2021phycoeval in units of expected substitutions per site by 33.76 million
years, the estimated age of this node in @Wood2022zenodo.
We provided these rates to ecoevolity for the *Cyrtodactylus* and *Gekko*
population pairs to estimate all 16 divergences in units of millions of years.

For each pair, we allowed the two descendant populations to have different
effective sizes, and we used the same gamma distributed priors on these
parameters as @Oaks2018paic, but with the mean rescaled for the mutation rate
per million years of each genera (@Oaks2018paic fixed the mutation rate to one
for all pairs).
The effective size of the ancestral population of each pair was estimated
relative to the mean of its two descendant populations with a gamma prior
distribution with a shape and mean of 100 and 1
(the same setting as @Oaks2018paic).

We analyzed the gecko data under a fixed, diffuse prior and a hyperprior on
divergence times:
$\tau \sim \textsf{Exponential}(\textsf{mean} = 20my))$
and
$\tau \sim \textsf{Exponential}(\textsf{mean} \sim \textsf{Exponential}(\textsf{mean} = 10my))$.
To assess the sensitivity of the results to prior assumptions about the
clumpiness of the Dirichlet process, we analyzed the data under two priors on
the concentration parameter:
$\tau \sim \textsf{Exponential}(\textsf{mean} = 293))$
and
$\tau \sim \textsf{Exponential}(\textsf{mean} = 10.84))$.
The former puts 50% of the prior probability on 16 independent divergences,
whereas the latter has a prior mean number of 8.5 divergences.

For each of the four combinations of divergence time and concentration priors,
we ran 10 MCMC chains for 150,000 generations, sampling every 100 generations.
To evaluate the convergence and mixing of the chains of each analysis,
we used the `pyco-sumchains` tool of pycoevolity
pycoevolity (Version X.X Commit XXXX)
to calculate the PSRF and ESS for all continuous parameters
and the log likelihood,
ignoring the beginning of each chain in increments of 100 samples.


## Results

### Validation of hyperprior implementation

Ecoevolity samples from the expected prior distribution
when data are ignored
(@sfig-priorcheck-mcmc)
and shows the expected posterior coverage behavior
when analyzing simulated data using the true generating
distributions as priors
(@sfig-coverage).

### Simulation-based assessment of hyperpriors on divergence times 

The introduction of hyperpriors on the divergence-time prior parameters
substantially mitigated the underestimation of divergence events observed under
fixed vague priors (@fig-sim-nevents).
For both the exponentially and uniformly distributed priors on time, the fixed
diffuse prior resulted in the underestimation of the number of divergence
events for 97% of the simulated data sets,
and the true number of divergence events was only included in the 95% posterior
credible set for 28% and 19% of the analyses (left column of @fig-sim-nevents).
When using a hyper prior on the mean and maximum of the exponential and uniform
prior,
the rate of underestimation of the number of divergence times drops to 42% and
39%, and the 95% credible set includes the true value 99 and 95% of the time
(middle column of @fig-sim-nevents).
The hyperprior models perform almost identically to analyses under the true
distribution of divergence times (middle versus right columns of
@fig-sim-nevents).

![
    Using a hyperprior on the (top-middle) mean and (bottom-middle) maximum
    time mitigates the underestimation of the number of divergence times ($k$).
    Heatmaps show the number of simulation replicates with a particular combination 
    of the true versus maximum *a posteriori* (MAP) number of divergence events
    For the exponential (top) and uniform (bottom) hyperprior,
    three models are compared: a fixed diffuse prior (left), a hyperprior model 
    (middle), and the true distribution used to simulate the data
    (right).
    Statistics reported in each panel include the proportion of simulation replicates
    for which the number of divergences is underestimated---$p(\hat{k} < k$---and for which
    the true number of divegences falls within the 95% credible set---$p(k \in 0.95\textsf{ CS})$,
    and the 
    median posterior probability across simulation replicates of the
    true number of divergence events---median $p(k|D)$.
](
    ./images/hp-sim-study-nevents-grid.svg
){
    #fig-sim-nevents
    fig-alt="True vs estimated number of events"
    fig-align="center"
}

Results are similar when looking at the posterior rank sum of the true
divergence model (the true clustering of population pairs to divergence times).
The posterior rank sum is calculated by ranking divergence models by their
approximate posterior probability (from highest to lowest) and summing the
probability down the list of models until the true model is found.
A value of zero means the model with the highest posterior probability is the
true model; a value of one means the true model was not sampled during the
analysis.
Under both the exponentially and uniformly distributed priors on time, the
hyperprior model performs significantly better (smaller posterior rank sums of
the true divergence model) than the fixed diffuse prior (left versus middle
violin of @fig-sim-model-rank) and indistinguishably from the true divergence
time distribution (middle versus right violin of @fig-sim-model-rank) according
to Wilcoxon signed-rank tests.

![
    Using a hyperprior on the (left) mean and (right) maximum time improves the
    inference of the true divergence model (clustering of population pairs to
    divergence times).
    Within each plot, the violin diagrams compare the posterior rank sum of the
    true divergence model across simulation replicates when analyzed under a
    (left) diffuse, (middle) hyperprior, and (right) the true distribution used
    to simulate the data.
    Brackets show the p-value of Wilcoxon signed-rank tests comparing the
    results of the diffuse prior to the hyperprior and the results of the
    hyperprior to the true distribution.
    Above the p-value, a greater-than/less-than symbol shows that the posterior
    rank sums on the left/right are more often larger, respectively; an equal
    sign means the the number replicates with a larger value on the left and
    right is equal.
](
    ./images/hp-sim-study-true-model-rank-sum-grid.svg
){
    #fig-sim-model-rank
    fig-alt="Comparing the posterior rank sum of the true divergence model"
    fig-align="center"
}

Similar to the number of divergences (@fig-sim-nevents),
the fixed diffuse prior causes high rates of underestimation
of the DP concentration
(83% and 89% under the exponential and uniform time priors;
@sfig-sim-conc)
and short posterior coverage
(72% and 63% coverage rates for the 95% credible interval under the exponential
and uniform time priors;
@sfig-sim-conc).
The time hyperprior model greatly improves the accuracy and coverage
of the DP concentration, and performs almost identically
to when the true time distribution is used
(@sfig-sim-conc).

All time prior settings show good accuracy and precision for estimating
divergence times,
but the coverage of the fixed diffuse prior is short whereas the
hyperprior model restores nominal coverage
(@sfig-sim-div-time).
All time prior settings perform similarly well in estimating the effective size
of the populations (@sfig-sim-pop-size).

The four MCMC chains of all the analyses of simulated data converged
quickly and mixed well.
When ignoring the first 201 samples of each chain, the log likelihood and all
parameters had an ESS > 363 and PSRF < 1.0017 across all analyses of simulated
data, so no values were highlighted for poor sampling in any of our plots
(@sfig-coverage,
@sfig-sim-conc,
@sfig-sim-div-time,
&
@sfig-sim-pop-size).

### Empirical test of Philippine PAIC model for gekkonids

Similar to the results of the simulated data sets, we see fewer divergence
events (more shared divergences) estimated when using a fixed diffuse prior
compared to the hyperprior model
(@fig-gecko-nevents).
Using a mean of 293 for the concentration of the Dirichlet process, the
hyperprior model supports 16 and 15 divergence events according to posterior
probability and Bayes factor, respectively, whereas the fixed diffuse prior
prefers 12 and 11 divergences
(@fig-gecko-nevents).
With a mean of 10.84 for the concentration of the Dirichlet process, the
hyperprior model prefers 13 and 14 divergence events according to posterior
probability and Bayes factor, respectively, whereas the fixed diffuse prior
supports 11 divergences for both measures
(@fig-gecko-nevents).

![
    The number of divergence events across 16 pairs of Philippine gecko
    populations estimated by ecoevolity under a (left column) fixed diffuse
    prior and (right column) hyperprior on divergence times, and two different
    priors on the concentration of the Dirichlet process (top and bottom rows).
    The bars show the approximate posterior and prior probabilities for the
    number of divergences, and approximate Bayes factors are shown for all
    values that were sampled by the MCMC chains.
](
    ./images/gecko-nevents-grid.svg
){
    #fig-gecko-nevents
    fig-alt="The estimated number of divergence events across 16 pairs of Philippine gecko populations"
    fig-align="center"
}

The distributions of divergences times marginalized over divergence models for
the 16 pairs of gecko populations were similar for all four combinations of
priors on time and the DP concentration
(@sfig-gecko-div-time-grid
and 
@sfig-gecko-div-time-grid-sans-palawan).
@fig-gecko-div-times
shows the marginal divergence times for 15 of the 16 pairs of gecko populations
for the analysis under the hyperprior model and DP concentration mean of 293.
The *Cyrtodactylus* populations from Borneo and Palawan diverged much earlier
than the other pairs and is removed from @fig-gecko-div-times to better
view the time distributions of the other pairs.
The estimated marginal divergence times of all 16 pairs are shown in
@sfig-gecko-div-time-grid.

![
    The estimated divergence times of 15 of the 16 pairs of Philippine gecko
    populations.
    The pair of *Cyrtodactylus* populations on Palawan and Borneo diverged much
    earlier than the other pairs and is not shown here; please see Supporting
    Information for plots of all 16 pairs.
    The white circle, black bars, and violin represent
    the posterior mean, 95% credible interval, and the full approximate
    posterior sample, respectively.
    The number at the end of the comparison labels represents the indices of
    unique divergences for the maximum *a posteriori* divergence model.
    The "G" and "C" next to the divergence index represents *Gekko* and
    *Cyrtodactylus*, respectively.
](
    ./images/geckos-combined-hyper-time-div-times-sans-palawan.svg
){
    #fig-gecko-div-times
    fig-alt="Estimated divergence times of 15 pairs of Philippine gecko populations"
    fig-align="center"
}

The 10 MCMC chains of all four models converged quickly and mixed well.
Based on the values of the ESS and PSRF calculated by `pyco-sumchains`, we
chose to ignore the first 101 samples of each chain (including the initial
state) and summarize the results of the remaining 1,400 samples of each chain,
for a total of 14,000 MCMC samples per model.
Across all the parameters and log likelihood of all four analyses, the smallest
ESS was 1014.8 and largest PSRF was 1.0056, suggesting good convergence to, and
sampling from, the posterior disribution.

## Discussion
** Somer papers to guide the discussion --> ?  McGaughran et al., 2022,...**
**ideas for discussion and text progression - draft**

### Hyperpriors on divergence times improve comparative biogeographic inferences
hyperpriors eliminate the downward bias on divergence events without requiring hyper-specific a priori knowledge
In most of times, researchers don't know much about the diversification historical events a population or species went through, and thus they don't know much about their demographic dynamics. Geomorphological and climatic events are sometimes used as proxies for the timing of divergence events, but these are often poorly constrained, highly uncertain, and are often the posterior interest of the comparative biogeographic inference, and so should not influence the prior.

Well-Calibrated Behavior and Posterior Robustness - MCMC sampling and Coverage of credible intervals? Simulated data analysis result

It's interesting that the model without the hyperprior on the mean divergence time is relatively robust to the prior on the concentration parameter. This robustness is likely the result of the strong penalty the prior on div times creates against adding div time parameters to the model. While the model with the hyperprior on the mean div time shows more honest sensitivity to the concentration parameter.

The number of divergence times and the concentration of the Dirichlet process are directly correlated,
so it is not surprising that we see similar patterns of underestimation of both variables
in the simulation results.
(@sfig-sim-conc and @sfig-sim-div-time).

The dimensionality of the effective population size parameters is static,
unlike the divergence time parameters. Thus it is not surprising that all the
prior settings perform similarity in estimating the population sizes
(@sfig-sim-pop-size).

### Re-evaluating the Comparative Biogeography of Philippine Gekkonids
The marked divergence between the posterior and prior number of events under the standard (non-hyperprior) model is consistent with the over-clustering bias described above: in the absence of the hyperprior, the model favors fewer, larger clusters of divergence events even when the prior places most of its mass on the many-independent-events scenario. The hyperprior model's posterior, by contrast, closely tracked its prior, suggesting this bias is substantially reduced when divergence times are allowed to vary hierarchically rather than being effectively pooled. This demonstrates the practical utility of hyperpriors in real-world comparative biogeographic analyses, highlighting their potential to improve inference in studies where prior knowledge is limited or uncertain. The analysis with the vague prior.

We can talk about how using estimates of mutation rates allowed us to analyze
all 16 pairs together, which provides more opportunities to identify shared
divergences.
The support for few, if any, shared divergences reinforces the original
findings that most divergences seem to be independent and thus not likely
influence by PAIC cycles.
However, there are caveats:
1.  Estimating the relative rates of mutation between the two genera is almost
    certainly error prone, and so we could be missing shared divergences
    between the genera due to getting the rates wrong.
2.  Only 7 of the 16 pairs are sampled from islands that were definitely
    connected during glacial periods. So, even combining the genera leaves us
    with relatively chances of finding shared divergences.

Broad Methodological Implications for the Field? - could be useful for past works that inferred highly synchronized multi-taxa events via vague fixed priors.

Scope and limitations?

A major limitation to the approach of comparing separate populations is that we
cannot learn about the relative rates of mutation during the analysis, and so
we have to know them *a priori*.
Fully phylogenetic approaches for estimating shared divergences can overcome
this by being able to estimate the relative rate of mutation across the tree
from the data.

# Acknowledgements

## References

::: {#refs}
:::

# Data Accessibility and Benefit-Sharing

# Author Contributions

# Supporting Information

## Validating MCMC sampling from prior distribution

To validate the ecoevolity implementation of divergence-time hyperpriors, we
first confirmed that the Markov chain Monte Carlo (MCMC) sampler correctly
samples from the specified prior distributions in the absence of data
(@sfig-priorcheck-mcmc).
For both the exponential hyperprior and uniform hyperprior models,
the MCMC samples show
excellent agreement
with the expected marginal prior distribution for the
number of divergence events,
time prior parameter (mean or maximum),
Dirichlet process concentration,
divergence time,
and effective population size
(@sfig-priorcheck-mcmc).
In all cases, a Kolmogorov-Smirnov test failed to reject that the MCMC samples
came from the expected marginal prior distributions.

![
    Ecoevolity successfully samples from the expected prior distribution of the
    model when no data are analyzed.
    The cumulative density of the MCMC samples (blue; empirical) closely
    matches the expected prior (orange; model).
    This is shown for models with an exponential hyperprior on the mean divergence time (left column)
    and uniform hyperprior on the maximum divergence time (right column),
    and for (from top to bottom row):
    The number of divergence events,
    hyperparameter of the prior on divergence times,
    concentration parameter of the Dirichlet process,
    divergence time of the first pair of populations,
    and effective size of the first pair of populations.
    Each plot includes the results of a Kolmogorov-Smirnov test, which was
    unable to reject that ecoevolity sampled from the expected distribution.
](
    ./images/prior-sampling-grid.svg
){
    #sfig-priorcheck-mcmc
    fig-alt="MCMC sampling from prior distribution"
    fig-align="center"
}

## Posterior coverage of divergence-time hyperparameter

Ecoevolity shows the expected posterior coverage when analyzing simulated data
under the correctly specified priors
(@sfig-coverage).
Generally, the 50% credible interval for a parameter contains the true value
approximately 50% of the time, barring sampling error.
Binomial tests fail to reject this expectation, with the possible exception
of the effective population size under the exponential hyperprior model
for which the p-value is 0.017.
However, if corrected for multiple tests, this result is likely due to chance.

![
    The Markov chain Monte Carlo algorithm of ecoevolity shows the expected
    posterior coverage behavior when the model is correctly specified (i.e.,
    the data are generated and analyzed under the same model).
    This is shown for models with an exponential hyperprior on the mean divergence time (left column)
    and uniform hyperprior on the maximum divergence time (right column),
    and for (from top to bottom row):
    The divergence time,
    effective size of the ancestral population of each pair,
    concentration parameter of the Dirichlet process,
    and hyperparameter of the prior on divergence times.
    Each plot shows the proportion of simulation replicates for which the true
    value falls within the 50% credible interval (approximated with the 50%
    highest posterior density interval [HPDI] from the MCMC samples), and
    the p-value of a binomial test comparing the observed proportion to 0.5.
    Each point error bar represent the mean and 50% HPDI from the MCMC samples.
](
    ./images/posterior-coverage-grid.svg
){
    #sfig-coverage
    fig-alt="Posterior coverage assessment"
    fig-align="center"
}

## Simulation results

![
    True versus estimated values of the concentration parameter of the
    Dirichlet process.
    For the exponential (top) and uniform (bottom) hyperprior,
    three models are compared: a fixed diffuse prior (left), a hyperprior model 
    (middle), and the true distribution used to simulate the data
    (right).
    Statistics reported in each panel include the proportion of simulation replicates
    for which the concentration is underestimated---$p(\hat{\alpha} < \alpha$---and for which
    the true concentration falls within the 95% credible set---$p(\alpha \in 0.95\textsf{ CS})$,
    and the 
    root mean square error (RMSE).
](
    ./images/hp-sim-study-concentration-grid.svg
){
    #sfig-sim-conc
    fig-alt="True vs estimated concentration"
    fig-align="center"
}

![
    True versus estimated values of divergence times.
    For the exponential (top) and uniform (bottom) hyperprior,
    three models are compared: a fixed diffuse prior (left), a hyperprior model 
    (middle), and the true distribution used to simulate the data
    (right).
    Statistics reported in each panel include the proportion of simulation replicates
    for which the divergence time is underestimated---$p(\hat{\tau} < \tau$---and for which
    the true time falls within the 95% credible set---$p(\tau \in 0.95\textsf{ CS})$,
    and the 
    root mean square error (RMSE).
](
    ./images/hp-sim-study-div-time-grid.svg
){
    #sfig-sim-div-time
    fig-alt="True vs estimated divergence times"
    fig-align="center"
}

![
    True versus estimated values of effective population size.
    For the exponential (top) and uniform (bottom) hyperprior,
    three models are compared: a fixed diffuse prior (left), a hyperprior model 
    (middle), and the true distribution used to simulate the data
    (right).
    Statistics reported in each panel include the proportion of simulation replicates
    for which the population size is underestimated---$p(\hat{N_{e}} < N_{e}$---and for which
    the true size falls within the 95% credible set---$p(N_{e} \in 0.95\textsf{ CS})$,
    and the 
    root mean square error (RMSE).
](
    ./images/hp-sim-study-pop-size-grid.svg
){
    #sfig-sim-pop-size
    fig-alt="True vs estimated effective population sizes"
    fig-align="center"
}

## Gecko results

![
    The divergence times of 16 pairs of Philippine gecko
    populations estimated by ecoevolity under a
    (left column) fixed diffuse prior and (right column) hyperprior on
    divergence times, and two different priors on the concentration of the
    Dirichlet process (top and bottom rows).
    The white circle, black bars, and violin represent
    the posterior mean, 95% credible interval, and the full approximate
    posterior sample, respectively.
    The number at the end of the comparison labels represents the indices of
    unique divergences for the maximum *a posteriori* divergence model.
    The "G" and "C" next to the divergence index represents *Gekko* and
    *Cyrtodactylus*, respectively.
](
    ./images/gecko-div-times-grid.svg
){
    #sfig-gecko-div-time-grid
    fig-alt="Estimated divergence times of 16 pairs of Philippine gecko populations"
    fig-align="center"
}

![
    The same results as in @sfig-gecko-div-time-grid, but with the oldest
    diverging pair of *Cyrtodactylus* populations from Palawan and Borneo
    removed.
](
    ./images/gecko-div-times-sans-palawan-grid.svg
){
    #sfig-gecko-div-time-grid-sans-palawan
    fig-alt="Estimated divergence times of 15 pairs of Philippine gecko populations"
    fig-align="center"
}
